# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    node: /home/org/industria/bin/node
    bundles:        [ ]
    filters:
        cssrewrite: ~
        less:
            node_paths: [ %kernel.root_dir%/../node_modules ]

braincrafted_bootstrap:
    jquery_path: %kernel.root_dir%/../vendor/components/jquery/jquery.min.js
    icon_prefix: fa
