security:
    encoders:
        App\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: app.user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true

        public:
            pattern: ^/
            form_login:
                login_path: app_login
                check_path: app_login_check
            logout: ~
            anonymous: ~

    access_control:
        - { path: ^/login$, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/oauth/v2/auth, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/admin, roles: [ ROLE_ADMIN ] }
        - { path: ^/usr, roles: [ ROLE_USER ] }
