security:
    encoders:
        App\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_SCOPE_R_PROFILE_EMAIL
            - ROLE_SCOPE_W_PROFILE
            - ROLE_SCOPE_W_GROUP
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_SCOPE_W_PROFILE_ADMIN
            - ROLE_SCOPE_W_PROFILE_CRED
            - ROLE_SCOPE_W_PROFILE_EMAIL
        ROLE_SCOPE_R_PROFILE_EMAIL: ROLE_SCOPE_R_PROFILE
        ROLE_SCOPE_W_PROFILE: ROLE_SCOPE_R_PROFILE
        ROLE_SCOPE_W_GROUP: ROLE_SCOPE_R_GROUP
        ROLE_SCOPE_W_PROFILE_ADMIN: ROLE_SCOPE_W_PROFILE
        ROLE_SCOPE_W_PROFILE_CRED: ROLE_SCOPE_W_PROFILE
        ROLE_SCOPE_W_PROFILE_EMAIL: ROLE_SCOPE_W_PROFILE

    providers:
        main:
            id: app.user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true

        public:
            pattern: ^/
            form_login:
                login_path: app_login
                check_path: app_login_check
            simple_preauth:
                authenticator: app.admin.security.apikey_authenticator
            logout: ~
            anonymous: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pub, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/oauth/v2/auth, role: ROLE_USER }
        - { path: ^/admin/apikeys, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin/oauth, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin/groups, methods: GET, role: ROLE_SCOPE_R_GROUP }
        - { path: ^/admin/groups, role: ROLE_SCOPE_W_GROUP }
        - { path: ^/admin/users, methods: GET, role: ROLE_SCOPE_R_PROFILE }
        - { path: ^/admin/users, role: ROLE_SCOPE_W_PROFILE }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/usr, roles: ROLE_USER }
