NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /admin/apidoc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

app_security:
    resource: "@AppBundle/Resources/config/routing/security.yml"

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix: admin
    type: rest
    requirements:
        id: "[0-9]+"

# Added here to avoid getting .{_format} appended by FOSRestBundle
admin_dashboard:
    path: admin/
    defaults:
        _controller: FrameworkBundle:Template:template
        template: AdminBundle::dashboard.html.twig

api:
    resource: "@AppBundle/Resources/config/routing/api.yml"
    prefix: /api
    type: rest
    
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix: /usr
    
user_public:
    resource: "@UserBundle/Resources/config/routing_public.yml"
    prefix: /pub
