user_profile:
    path: profile
    defaults:
        _controller: UserBundle:Profile:index
    requirements:
        _method: GET

user_app_auth_delete:
    path: app_auth_delete
    defaults:
        _controller: UserBundle:Profile:deleteAuthorizedApp
    requirements:
        _method: DELETE
        
user_put_email_addresses:
    path: mailaddr
    defaults:
        _controller: UserBundle:Profile:putEmailAddresses
    requirements:
        _method: PUT

user_kill_session:
    path: kill-session
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: logout

user_change_password:
    path: passwd
    defaults:
        _controller: UserBundle:Profile:changePassword
    requirements:
        _method: GET|POST
