api_user_get:
    pattern: user
    defaults:
        _controller: User\Controller\Api\UserController::getAction
        _format: ~

api_group:
    name_prefix: api_
    resource: User\Controller\Api\GroupController
    type: rest

api_property:
    name_prefix: api_
    resource: User\Controller\Api\PropertyController
    type: rest
