user_email_verify:
    path: email/verify/{id}/{verificationCode}
    defaults:
        _controller: UserBundle:PublicEmail:verifyEmail

user_email_resend:
    path: email/verify
    defaults:
        _controller: UserBundle:PublicEmail:resendVerification

user_password_reset:
    path: forgot/reset/{username}/{verificationCode}
    defaults:
        _controller: UserBundle:ResetPassword:resetPassword

user_password_forgot:
    path: forgot
    defaults:
        _controller: UserBundle:ResetPassword:forgotPassword
