user_profile:
    path: profile
    defaults:
        _controller: UserBundle:Profile:index
    methods: GET

user_app_auth_delete:
    path: oauthapp
    defaults:
        _controller: UserBundle:Profile:deleteAuthorizedApp
    methods: DELETE

user_put_email_addresses:
    path: mailaddr/{addr}
    defaults:
        _controller: UserBundle:Profile:putEmailAddresses
    methods: PUT

user_post_email_addresses:
    path: mailaddr
    defaults:
        _controller: UserBundle:Profile:postEmailAddresses
    methods: POST

user_post_group:
    path: group
    defaults:
        _controller: UserBundle:Profile:postGroup
    methods: POST

user_delete_group:
    path: group
    defaults:
        _controller: UserBundle:Profile:deleteGroup
    methods: DELETE

user_kill_session:
    path: kill-session
    defaults:
        _controller: UserBundle:User:killSession
        route: logout

user_change_password:
    path: passwd
    defaults:
        _controller: UserBundle:Profile:changePassword
    methods: [GET, POST]
