user_profile:
    path: profile
    defaults:
        _controller: UserBundle:Profile:index
    requirements:
        _method: GET

user_app_auth_delete:
    path: oauthapp
    defaults:
        _controller: UserBundle:Profile:deleteAuthorizedApp
    requirements:
        _method: DELETE

user_put_email_addresses:
    path: mailaddr/{addr}
    defaults:
        _controller: UserBundle:Profile:putEmailAddresses
    requirements:
        _method: PUT

user_post_email_addresses:
    path: mailaddr
    defaults:
        _controller: UserBundle:Profile:postEmailAddresses
    requirements:
        _method: POST

user_put_property:
    path: property/{property}
    defaults:
        _controller: UserBundle:Profile:putProperty
    requirements:
        _method: PUT

user_post_group:
    path: group
    defaults:
        _controller: UserBundle:Profile:postGroup
    requirements:
        _method: POST

user_delete_group:
    path: group
    defaults:
        _controller: UserBundle:Profile:deleteGroup
    requirements:
        _method: DELETE

user_kill_session:
    path: kill-session
    defaults:
        _controller: UserBundle:User:killSession
        route: logout

user_change_password:
    path: passwd
    defaults:
        _controller: UserBundle:Profile:changePassword
    requirements:
        _method: GET|POST
