- hosts: all
  tasks:
    - apt_repository: repo="deb http://ftp.us.debian.org/debian wheezy-backports main" state=present
    - name: Install packages
      apt: name={{ item }} state=present update_cache=yes
      with_items:
        - apache2
        - libapache2-mod-php5
        - php5
        - php5-sqlite
        - git
        - nodejs-legacy
        - curl
    - shell: curl https://www.npmjs.com/install.sh | sh creates=/usr/bin/npm
    - apache2_module: name=php5 state=present
      notify: reload httpd
    - shell: creates=/usr/local/bin/composer php -r "readfile('https://getcomposer.org/installer');" | php -- --install-dir=/usr/local/bin --filename=composer
    - lineinfile: regexp='DocumentRoot' line='DocumentRoot /var/www/web' dest=/etc/apache2/sites-available/default state=present
      notify: reload httpd
    - replace: regexp='AllowOverride None' replace='AllowOverride All' dest=/etc/apache2/sites-available/default
    - command: a2enmod rewrite creates=/etc/apache2/mods-enabled/rewrite.load
      notify: reload httpd
    - command: cp -r /vagrant/{{ item }} /var/www/{{ item }}
      with_items:
        - app
        - web
        - composer.json
        - composer.lock
        - package.json
    - shell: base64 < /dev/urandom | head -1
      register: random
    - template: src=parameters.yml.j2 dest=/var/www/app/config/parameters.yml
    - composer: working_dir=/var/www no_scripts=yes
    - npm: path=/var/www
    - command: php app/console {{ item }} -n chdir=/var/www
      with_items:
        - cache:clear
        - assets:install
        - assetic:dump
        - doctrine:migrations:migrate
    - file: path=/var/www/{{ item }} owner=www-data mode=u+rw,o=r recurse=yes state=directory
      with_items:
        - app/cache
        - app/logs
    - command: sed s/app\.php/app_dev.php/ -i /var/www/web/.htaccess
    - service: name=apache2 state=started 
  handlers:
   - name: reload httpd
     service: name=apache2 state=reloaded
