admin_user_property:
    resource: app.admin.user_property.controller
    type: rest
    name_prefix: admin_user_property_
    prefix: users/properties
    requirements:
        id: "[0-9]+"

admin_user:
    resource: app.admin.user.controller
    type: rest
    name_prefix: admin_user_
    prefix: users
    requirements:
        id: "[0-9]+|([0-9A-F]{8}-([0-9A-F]{4}-){3}[0-9A-F]{12})"

admin_group:
    resource: app.admin.group.controller
    type: rest
    name_prefix: admin_group_
    prefix: groups
    requirements:
        id: "%?[a-z0-9_]+"

admin_oauth_client:
    resource: app.admin.oauth.client.controller
    type: rest
    name_prefix: admin_oauth_client_
    prefix: oauth/clients
    requirements:
        id: "[0-9]+"

admin_apikey:
    resource: app.admin.apikey.controller
    type: rest
    name_prefix: admin_apikey_
    prefix: apikeys
    requirements:
        id: "[0-9]+"

admin_dashboard:
    path: dashboard
    defaults:
        _controller: FrameworkBundle:Template:template
        template: AdminBundle::dashboard.html.twig
        _format: html
