admin_user:
    resource: Admin\Controller\UserController
    type: rest
    name_prefix: admin_user_
    prefix: users
    requirements:
        user: "[0-9A-F]{8}-([0-9A-F]{4}-){3}[0-9A-F]{12}"

admin_user_email:
    resource: Admin\Controller\UserEmailController
    type: rest
    name_prefix: admin_user_email_
    requirements:
        user: "[0-9A-F]{8}-([0-9A-F]{4}-){3}[0-9A-F]{12}"
        email: "[0-9]+"

admin_group:
    resource: Admin\Controller\GroupController
    type: rest
    name_prefix: admin_group_
    prefix: groups
    requirements:
        group: "(?!(new|batch)$)%?[a-z0-9_]+"

admin_oauth_client:
    resource: Admin\Controller\OAuthClientController
    type: rest
    name_prefix: admin_oauth_client_
    prefix: oauth/clients
    requirements:
        client: "[0-9]+"

admin_apikey:
    resource: Admin\Controller\ApiKeyController
    type: rest
    name_prefix: admin_apikey_
    prefix: apikeys
    requirements:
        apikey: "[0-9]+"

admin_audit:
    resource: Admin\Controller\AuditController
    type: rest
    name_prefix: admin_audit_
    prefix: auditlog
    requirements:
        id: "[0-9]+"

admin_dashboard:
    path: dashboard
    defaults:
        _controller: FrameworkBundle:Template:template
        template: AdminBundle::dashboard.html.twig
        _format: html
