admin_user:
    resource: app.admin.user.controller
    type: rest
    name_prefix: admin_user_
    prefix: users

admin_group:
    resource: app.admin.group.controller
    type: rest
    name_prefix: admin_group_
    prefix: groups

admin_oauth_client:
    resource: app.admin.oauth.client.controller
    type: rest
    name_prefix: admin_oauth_client_
    prefix: oauth/clients

admin_apikey:
    resource: app.admin.apikey.controller
    type: rest
    name_prefix: admin_apikey_
    prefix: apikeys
